Add option in `RustConfig` to customize the build.
emk/heroku-buildpack-rust pull request #41
Opened 2019-02-11 20:44 UTC by yageek

Adds the `CARGO_BUILD_FLAGS` option to be able to customize the build command.

2019-02-12 12:30 UTC, emk requested changes
Thank you for submitting this PR! I have a number of suggestions below about how we could tweak this to be as useful to as many people as possible. Thank you for considering them!

2019-02-12 12:30 UTC, emk commented on bin/compile
> +CARGO_BUILD_FLAGS=""
We definitely want to build with `--release` by default as before. So as a minimum, we'd need:

```suggestion
RUST_CARGO_BUILD_FLAGS="--release"
```

Also, I'd like to name this `RUST_CARGO_BUILD_FLAGS` by default, because that will make things clearer in multi-build-pack situations. Yes, some of the existing flags don't have a `RUST_*` prefix. I plan to fix that some day.

2019-02-12 12:30 UTC, emk commented on bin/compile
> +  cargo build "$CARGO_BUILD_FLAGS"
```suggestion
  cargo build $RUST_CARGO_BUILD_FLAGS
```
You definitely don't want the `"` characters around `$RUST_CARGO_BUILD_FLAGS` here, because that will cause the shell to consider all the flags to be one, single command-line argument.

2019-02-12 12:30 UTC, emk commented on bin/compile
> +# `CARGO_BUILD_FLAGS` default build command
```suggestion
# Default build flags to pass to `cargo build`.
```

2019-02-12 12:30 UTC, emk commented on README.md
> +By default the command line used to build the rust binary is `cargo build --release`.
This help message should explain how to actually set the build flags, and what the default value of `RUST_CARGO_BUILD_FLAGS` is. This will help users figure out how to customize it!

2019-02-12 12:47 UTC, yageek commented on bin/compile
> +CARGO_BUILD_FLAGS=""
Oupss. I forgot to commit my last changes... I'll update it

2019-04-17 18:18 UTC, emk approved these changes

2019-04-17 18:18 UTC, merged

2019-04-17 18:18 UTC, emk commented
Thank you for your change, and my apologies for taking so long to follow up on it!